name: Guilds
version: '${project.version}'
main: net.devscape.project.guilds.Guilds
api-version: 1.13
authors: [DevScape]
depend:
  - Vault
description: Amazing guild rich-feature plugin.
commands:
  guilds:
    description: Command for guilds.
    aliases:
      - guild
      - g